name: Test and Push

on:
  push:
    branches:
      - main  # Replace 'main' with the branch you want to trigger the workflow on

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # Replace with your required Java version
          distribution: 'adopt'  # You can use 'adopt', 'zulu', or 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install dependencies
        run: mvn install -DskipTests=true  # Skip tests during dependency installation

      - name: Run tests
        run: mvn test  # Replace with your test command
        continue-on-error: false  # Ensure the workflow fails if tests fail

  push:
    needs: test
    runs-on: ubuntu-latest
    if: ${{ success() }}  # Only run this job if the test job succeeds
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Push changes
        run: |
          git config user.name "CredBibek "
          git config user.email "bibek.das@credresolve.com"
          git push origin main  # Replace 'main' with your branch name
